weather_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('WAREHOUSE_HOST') }}"
      user: "{{ env_var('WAREHOUSE_USER') }}"
      password: "{{ env_var('WAREHOUSE_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('WAREHOUSE_DB') }}"
      schema: analytics
      threads: 2
  target: dev
